/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Me
         * @description Resolve the bearer of an access token. Added in Phase 8 so the frontend never has to
         *     decode a JWT client-side to find out who it's logged in as.
         *
         *     Deliberately not behind `rate_limit_auth` (unlike /register and /login): that bucket is
         *     keyed by client IP with a low cap meant to blunt credential stuffing, and this route is hit
         *     on every app load and every token refresh -- rate-limiting it would throttle normal use,
         *     and it's not a credential-guessing surface (an attacker needs a valid token already).
         */
        get: operations["me_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Refresh */
        post: operations["refresh_auth_refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register */
        post: operations["register_auth_register_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/organizations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List My Organizations */
        get: operations["list_my_organizations_organizations_get"];
        put?: never;
        /** Create Organization */
        post: operations["create_organization_organizations_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/organizations/{org_id}/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Members */
        get: operations["list_members_organizations__org_id__members_get"];
        put?: never;
        /** Add Member */
        post: operations["add_member_organizations__org_id__members_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/organizations/{org_id}/members/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove Member */
        delete: operations["remove_member_organizations__org_id__members__user_id__delete"];
        options?: never;
        head?: never;
        /** Change Member Role */
        patch: operations["change_member_role_organizations__org_id__members__user_id__patch"];
        trace?: never;
    };
    "/organizations/{org_id}/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Projects */
        get: operations["list_projects_organizations__org_id__projects_get"];
        put?: never;
        /** Create Project */
        post: operations["create_project_organizations__org_id__projects_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{project_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Project */
        get: operations["get_project_projects__project_id__get"];
        put?: never;
        post?: never;
        /** Delete Project */
        delete: operations["delete_project_projects__project_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{project_id}/analytics/query": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Run Query */
        post: operations["run_query_projects__project_id__analytics_query_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{project_id}/chat/ask": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ask */
        post: operations["ask_projects__project_id__chat_ask_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{project_id}/dashboard/generate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Generate Dashboard */
        post: operations["generate_dashboard_projects__project_id__dashboard_generate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{project_id}/datasets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Datasets
         * @description A project's datasets, newest first -- so `[0]` is the one query/dashboard/chat actually run
         *     against (`dataset_deps.get_latest_dataset` resolves the same row).
         *
         *     Added in Phase 8 M3: without it the frontend could only ever see a semantic model in the
         *     response of the discovery job it just polled, so a page reload left the UI unable to tell
         *     whether the project had any data at all. Returns full semantic models rather than a summary
         *     plus a detail route -- one upload is one row and a model is a few KB, so the simpler shape
         *     covers both "does this project have data" and "show me the current model" in one request.
         */
        get: operations["list_datasets_projects__project_id__datasets_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{project_id}/datasets/{dataset_id}/mapping-decisions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Review Mappings
         * @description Confirm or reject column-to-semantic-type mappings. The engine computes only on "auto" or
         *     "confirmed" mappings (SemanticModel.trusted), so this is how a person promotes a correct
         *     low-confidence guess, or vetoes a wrong one POC 1 was sure about.
         *
         *     Writes a NEW Dataset row -- same stored files, updated semantic model -- rather than editing this
         *     one. ResultCache and PipelineCache are only correct because a Dataset row never changes after it's
         *     created; a new version gets its own cache entries, becomes "the" dataset for the project
         *     immediately (newest wins), and keeps the previous version intact. One batch is one version.
         */
        post: operations["review_mappings_projects__project_id__datasets__dataset_id__mapping_decisions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{project_id}/schema/discover": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Discover Schema
         * @description Enqueues discovery instead of running it inline (Phase 7 M3) -- LLM-heavy relationship
         *     reasoning could take a while for a large/many-file upload, and doing that inside the HTTP
         *     request meant the client's connection had to stay open the whole time. Poll
         *     GET .../schema/jobs/{id} for the result; `run_schema_discovery()` itself, and every
         *     validation rule below, are unchanged from the synchronous version.
         */
        post: operations["discover_schema_projects__project_id__schema_discover_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{project_id}/schema/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Discovery Job */
        get: operations["get_discovery_job_projects__project_id__schema_jobs__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AddMemberRequest */
        AddMemberRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
            role: components["schemas"]["Role"];
        };
        /**
         * AnalyticalQuery
         * @description The Analytical Query / AST — see architecture doc §10 and class_diagram.md.
         */
        AnalyticalQuery: {
            /** Dimension */
            dimension?: string | null;
            growth?: components["schemas"]["GrowthSpec"] | null;
            having_override?: components["schemas"]["HavingClause"] | null;
            /** Limit */
            limit?: number | null;
            /** Metric */
            metric: string;
            operation: components["schemas"]["OperationType"];
            sort?: components["schemas"]["SortSpec"] | null;
            time_filter?: components["schemas"]["TimeFilter"] | null;
        };
        /**
         * Answer
         * @description POC 4's actual deliverable. `refused=True` means `result` is None and `explanation` is a
         *     deterministic reason string (from the planner's own refusal, or from QuestionValidator) --
         *     InsightGenerator is never invoked for a refused question, see class_diagram.md's resolved
         *     "Insight LLM prompt scope" question.
         */
        Answer: {
            /** Data Through */
            data_through?: string | null;
            /** Explanation */
            explanation: string;
            intent?: components["schemas"]["QuestionIntent"] | null;
            /**
             * Queries
             * @default []
             */
            queries: components["schemas"]["AnalyticalQuery"][];
            /** Question */
            question: string;
            /** Reason */
            reason?: string | null;
            /** Refused */
            refused: boolean;
            result?: components["schemas"]["QuestionResult"] | null;
        };
        /** AskRequest */
        AskRequest: {
            /** Question */
            question: string;
        };
        /** Body_discover_schema_projects__project_id__schema_discover_post */
        Body_discover_schema_projects__project_id__schema_discover_post: {
            /** Files */
            files: string[];
            /** Name */
            name?: string | null;
        };
        /**
         * CategoryDelta
         * @description One dimension value's current-vs-comparison comparison, for a GROWTH_BY_DIMENSION answer.
         *
         *     `current_value`/`comparison_value` are zero-filled (never None) when a dimension value is
         *     missing from one side -- see class_diagram.md's resolved "category-set mismatch" question.
         *     `pct_change` is None (not an error) when `comparison_value == 0`, since it's undefined there;
         *     ranking uses `delta`, not `pct_change`, for exactly this reason.
         */
        CategoryDelta: {
            /** Comparison Value */
            comparison_value: number;
            /** Current Value */
            current_value: number;
            /** Delta */
            delta: number;
            /** Dimension Value */
            dimension_value: string;
            /** Pct Change */
            pct_change?: number | null;
        };
        /** ChangeRoleRequest */
        ChangeRoleRequest: {
            role: components["schemas"]["Role"];
        };
        /** ComponentSpec */
        ComponentSpec: {
            /** Component Id */
            component_id: string;
            /** Dimension */
            dimension?: string | null;
            /** Metric Name */
            metric_name: string;
            /**
             * Rationale
             * @default
             */
            rationale: string;
            /** Time Grain */
            time_grain?: string | null;
            type: components["schemas"]["ComponentType"];
        };
        /**
         * ComponentType
         * @enum {string}
         */
        ComponentType: "kpi" | "bar_chart" | "pie_chart" | "table" | "line_chart";
        /** CreateOrganizationRequest */
        CreateOrganizationRequest: {
            /** Name */
            name: string;
        };
        /** CreateProjectRequest */
        CreateProjectRequest: {
            /** Name */
            name: string;
        };
        /** DatasetOut */
        DatasetOut: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /**
             * Project Id
             * Format: uuid
             */
            project_id: string;
            semantic_model: components["schemas"]["SemanticModel"];
        };
        /** Entity */
        Entity: {
            /** Fields */
            fields: components["schemas"]["SemanticField"][];
            /** Name */
            name: string;
        };
        /** FilterSpec */
        FilterSpec: {
            /** Dimension */
            dimension: string;
            /** Label */
            label: string;
        };
        /** GrowthSpec */
        GrowthSpec: {
            comparison_period: components["schemas"]["TimeFilter"];
            current_period: components["schemas"]["TimeFilter"];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HavingClause */
        HavingClause: {
            /** Field */
            field: string;
            /** Operator */
            operator: string;
            /** Value */
            value: number;
        };
        /** HydratedComponent */
        HydratedComponent: {
            result: components["schemas"]["MetricResult"];
            spec: components["schemas"]["ComponentSpec"];
        };
        /** HydratedDashboard */
        HydratedDashboard: {
            /** Components */
            components?: components["schemas"]["HydratedComponent"][];
            /** Filters */
            filters?: components["schemas"]["FilterSpec"][];
            /**
             * Narrative
             * @default
             */
            narrative: string;
            /** Title */
            title: string;
        };
        /** JobOut */
        JobOut: {
            dataset?: components["schemas"]["DatasetOut"] | null;
            /** Error */
            error?: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Project Id
             * Format: uuid
             */
            project_id: string;
            status: components["schemas"]["JobStatus"];
        };
        /**
         * JobStatus
         * @enum {string}
         */
        JobStatus: "pending" | "running" | "done" | "failed";
        /** LoginRequest */
        LoginRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
        };
        /** LogoutRequest */
        LogoutRequest: {
            /** Refresh Token */
            refresh_token: string;
        };
        /** MappingDecision */
        MappingDecision: {
            /**
             * Decision
             * @enum {string}
             */
            decision: "confirm" | "reject";
            /** Source Column */
            source_column: string;
            /** Source File */
            source_file: string;
        };
        /** MappingDecisionsRequest */
        MappingDecisionsRequest: {
            /** Decisions */
            decisions: components["schemas"]["MappingDecision"][];
        };
        /**
         * MeOut
         * @description Identity only. Org membership and roles deliberately aren't duplicated here --
         *     GET /organizations already returns every org the caller belongs to with its `my_role`, and
         *     two sources for the same RBAC fact is how they drift apart.
         */
        MeOut: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Email */
            email: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
        };
        /** MemberOut */
        MemberOut: {
            /** Email */
            email: string;
            role: components["schemas"]["Role"];
            /**
             * User Id
             * Format: uuid
             */
            user_id: string;
        };
        /**
         * MetricResult
         * @description One typed shape for both scalar and grouped results (hld.md's resolved open question):
         *     `value` for a plain KPI, `rows` for a grouped/dimension query.
         *
         *     `shape` is the authoritative signal for which one applies -- mirrors CompiledQuery's own
         *     `result_shape` field (set from it directly in QueryExecutor.execute), rather than inferring
         *     shape from which of `value`/`rows` happens to be non-None. That inference used to be the only
         *     signal, and broke on a real, previously-undiscovered case (found via
         *     poc4_nl_chatbot/tests/test_real_olist_integration.py): a scalar GROWTH query whose comparison
         *     period matches zero rows produces a legitimately-NULL value (`NULLIF(0, 0)`'s division), which
         *     is a valid scalar result -- "undefined," not "absent, so this must actually be a grouped
         *     result" -- but the old presence-based invariant couldn't tell the difference and raised
         *     instead of returning `value=None`. `shape="scalar"` with `value=None` now means exactly that:
         *     a real, computed, mathematically-undefined answer.
         */
        MetricResult: {
            /** Caveats */
            caveats?: string[];
            /**
             * Format
             * @default number
             * @enum {string}
             */
            format: "money" | "count" | "percent" | "number";
            metadata: components["schemas"]["QueryMetadata"];
            /** Metric Name */
            metric_name: string;
            /** Rows */
            rows?: {
                [key: string]: unknown;
            }[] | null;
            /**
             * Shape
             * @enum {string}
             */
            shape: "scalar" | "grouped";
            /**
             * Truncated
             * @default false
             */
            truncated: boolean;
            /** Value */
            value?: number | null;
        };
        /**
         * OperationType
         * @enum {string}
         */
        OperationType: "aggregate" | "group_by" | "growth";
        /** OrganizationOut */
        OrganizationOut: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            my_role: components["schemas"]["Role"];
            /** Name */
            name: string;
            /** Slug */
            slug: string;
        };
        /** ProjectOut */
        ProjectOut: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /**
             * Org Id
             * Format: uuid
             */
            org_id: string;
        };
        /** QueryMetadata */
        QueryMetadata: {
            /** Execution Time Ms */
            execution_time_ms: number;
            /** Row Count */
            row_count: number;
            /** Sql */
            sql: string;
        };
        /**
         * QuestionIntent
         * @description The planner's structured output for one natural-language question.
         *
         *     `answerable=False` is the planner's own refusal signal (architecture doc §16) -- checked
         *     again, independently, by QuestionValidator once the intent is assembled into a real
         *     AnalyticalQuery (defense in depth, same pattern POC 2's ASTValidator / POC 3's
         *     DashboardValidator already establish for their own input shapes).
         */
        QuestionIntent: {
            /** Answerable */
            answerable: boolean;
            /** Dimension */
            dimension?: string | null;
            /** Metric Name */
            metric_name?: string | null;
            operation?: components["schemas"]["QuestionOperation"] | null;
            /** Reason */
            reason?: string | null;
            time_expression?: components["schemas"]["TimeExpression"] | null;
        };
        /**
         * QuestionOperation
         * @description A POC 4-level planning concept -- NOT insightflow_core's OperationType. GROWTH_BY_DIMENSION
         *     has no single-node representation in the shared AST (AnalyticalQuery's own validator makes
         *     `dimension` and `growth` mutually exclusive); QueryAssembler decomposes it into two ordinary
         *     GROUP_BY queries. See class_diagram.md's banner note for the full reasoning.
         * @enum {string}
         */
        QuestionOperation: "aggregate" | "group_by" | "growth" | "growth_by_dimension";
        /**
         * QuestionResult
         * @description Exactly one of the two fields is set: `metric_result` for AGGREGATE/GROUP_BY/GROWTH,
         *     `category_deltas` for GROWTH_BY_DIMENSION. Wraps insightflow_core's MetricResult unmodified
         *     rather than replacing it -- see class_diagram.md's note on minimal-change pluggability.
         */
        QuestionResult: {
            /** Category Deltas */
            category_deltas?: components["schemas"]["CategoryDelta"][] | null;
            /**
             * Format
             * @default number
             * @enum {string}
             */
            format: "money" | "count" | "percent" | "number";
            metric_result?: components["schemas"]["MetricResult"] | null;
        };
        /** RefreshRequest */
        RefreshRequest: {
            /** Refresh Token */
            refresh_token: string;
        };
        /** RegisterRequest */
        RegisterRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
        };
        /** Relationship */
        Relationship: {
            /** Confidence */
            confidence: number;
            /** Direction */
            direction: string;
            /** From Field */
            from_field: string;
            /** To Field */
            to_field: string;
            /**
             * Validated
             * @default true
             */
            validated: boolean;
        };
        /**
         * Role
         * @description RBAC roles per CLAUDE.md §4, ordered weakest to strongest -- see auth/rbac.py for the
         *     ordering logic that `require_role` depends on.
         * @enum {string}
         */
        Role: "viewer" | "analyst" | "admin" | "owner";
        /** SemanticField */
        SemanticField: {
            /** Confidence */
            confidence: number;
            /** Name */
            name: string;
            /** Source Column */
            source_column: string;
            /** Source File */
            source_file: string;
            /**
             * Status
             * @default auto
             * @enum {string}
             */
            status: "auto" | "needs_confirmation" | "confirmed" | "rejected";
        };
        /** SemanticModel */
        SemanticModel: {
            /** Entities */
            entities: components["schemas"]["Entity"][];
            /** Relationships */
            relationships: components["schemas"]["Relationship"][];
        };
        /** SortSpec */
        SortSpec: {
            /**
             * Direction
             * @default desc
             */
            direction: string;
            /** Field */
            field: string;
        };
        /**
         * TimeExpression
         * @enum {string}
         */
        TimeExpression: "this_month" | "last_month" | "this_quarter" | "last_quarter" | "this_year" | "last_year" | "all_time";
        /** TimeFilter */
        TimeFilter: {
            /**
             * End Date
             * Format: date
             */
            end_date: string;
            /**
             * Start Date
             * Format: date
             */
            start_date: string;
        };
        /** TokenPair */
        TokenPair: {
            /** Access Token */
            access_token: string;
            /** Refresh Token */
            refresh_token: string;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    login_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenPair"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LogoutRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    me_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeOut"];
                };
            };
        };
    };
    refresh_auth_refresh_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenPair"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    register_auth_register_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenPair"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    list_my_organizations_organizations_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrganizationOut"][];
                };
            };
        };
    };
    create_organization_organizations_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateOrganizationRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrganizationOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_members_organizations__org_id__members_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                org_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemberOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_member_organizations__org_id__members_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                org_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddMemberRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemberOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remove_member_organizations__org_id__members__user_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
                org_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    change_member_role_organizations__org_id__members__user_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
                org_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangeRoleRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemberOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_projects_organizations__org_id__projects_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                org_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_project_organizations__org_id__projects_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                org_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateProjectRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_project_projects__project_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_project_projects__project_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_query_projects__project_id__analytics_query_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AnalyticalQuery"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MetricResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ask_projects__project_id__chat_ask_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AskRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Answer"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    generate_dashboard_projects__project_id__dashboard_generate_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HydratedDashboard"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_datasets_projects__project_id__datasets_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DatasetOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    review_mappings_projects__project_id__datasets__dataset_id__mapping_decisions_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                dataset_id: string;
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MappingDecisionsRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DatasetOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    discover_schema_projects__project_id__schema_discover_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_discover_schema_projects__project_id__schema_discover_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_discovery_job_projects__project_id__schema_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
