"""phase 7 m3 jobs table

Revision ID: 678e27211cd0
Revises: b55ea553a273
Create Date: 2026-09-13 18:26:46.267238

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '678e27211cd0'
down_revision: Union[str, None] = 'b55ea553a273'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'DONE', 'FAILED', name='job_status'), nullable=False),
    sa.Column('dataset_id', sa.UUID(), nullable=False),
    sa.Column('dataset_name', sa.String(length=200), nullable=False),
    sa.Column('storage_prefix', sa.String(length=500), nullable=False),
    sa.Column('filenames', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('jobs')
    # ### end Alembic commands ###

    # Not auto-generated: same Phase 6 gotcha (b55ea553a273's downgrade) -- dropping the table
    # doesn't drop the Postgres native ENUM type it used, so a downgrade -> upgrade cycle fails
    # with "type job_status already exists" on the next upgrade otherwise.
    sa.Enum(name='job_status').drop(op.get_bind(), checkfirst=True)
